### ISSUE TITLE
Browse navigation

### ISSUE THREAD

**Issue by jaseiler** [researchcompendia/researchcompendia#55] opened 2013-11-08 17:49 UTC
One of Victoria's friends suggested continuous scroll (which I, personally, hate) but if not that, there needs to be a page change bar at the bottom as well as the top.  Also, both should probably float right.

**Comment by codersquid** [comment] 2013-11-08 18:00
I also don't like continuous scroll. I don't think the user experience for that is good in terms of accessibility (on top of me just not finding the experience to be very pleasant).

**Comment by codersquid** [comment] 2013-11-08 18:03
For the continuous scroll, if it turns out to be a requirement, I suggest opening an issue for that to be done in the next release versus the current one.

For the page changing, I have something at the top right now, but agree it should also be included on the bottom.

I also want to allow an easy way for people to change the number of items on a page -- I don't have that finished, but have made it possible to add some javascript to the template to get the backend to do it.

**Comment by codersquid** [comment] 2013-11-08 18:05
I'll close #14 as a duplicate of this, since this one has more information.

**Comment by codersquid** [comment] 2013-11-15 16:06
you've added the pagination on the bottom, so I'm closing this issue now.

**Closed as completed by codersquid** 2013-11-15 16:06 UTC
Labels: Ready
